name: 07 - Contexts
run-name: 07 - Contexts | DEBUG - ${{ inputs.debug }}
on: 
   # push:
    workflow_dispatch: 
        inputs:
          debug: 
             type: boolean
             default: false
             description: ¿Modo depuracion?

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: 'job'
            MY_OVERWRITTEN_VAR: 'job'
        steps:
            - name: Show Info
              run: |
                echo "Nombre del evento: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Flujo de trabajo: ${{ github.workflow }}"
                echo "ID de ejecución: ${{ github.run_id }}"
                echo "Número de ejecución: ${{ github.run_number }}"
            - name: Retrieve Variable
              run: |
                 echo "${{ vars.MY_VAR }}"
                 echo "${{ vars.ORG_VAR }}"
            - name: Print Env Variables
              env:
                MY_OVERWRITTEN_VAR: 'step'
              run: |
                 echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                 echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: Print Env Variables
              run: |
                 echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                 echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"